# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
	# The most common configuration options are documented and commented below.
	# For a complete reference, please see the online documentation at
	# https://docs.vagrantup.com.

	# Every Vagrant development environment requires a box. You can search for
	# boxes at https://vagrantcloud.com/search.
	config.vm.box = "geerlingguy/ubuntu1604"

	# The url from where the 'config.vm.box' box will be fetched if it
	# doesn't already exist on the user's system.
	config.vm.box_url = "https://app.vagrantup.com/geerlingguy/boxes/ubuntu1604"

	# memory increase
	config.vm.provider "virtualbox" do |v|
        v.memory = 4964
        v.cpus = 4
    end
					  
	PATH_VAGRANT_PROJECT=File.dirname(__FILE__)
	
	
	
	###############
	#####  LOCAL PROVISIONERS INSTEAD OF DOWNLOAD
	
	
	# forward ports

	# hoverfly
	config.vm.network :forwarded_port, guest: 8500, host: 8500
	config.vm.network :forwarded_port, guest: 8888, host: 8888	
	
	# all files here will be added to home
	config.vm.synced_folder "#{PATH_VAGRANT_PROJECT}\\vagrant-home\\", "//home/vagrant/vagrant-home/"
	
  
	# Use shell script to provision
	config.vm.provision "shell", inline: <<-SHELL
			
	
		# update
		apt-get update	
		
		# install docker
		apt-get -y install docker.io


		###############
		##### HOVERFLY
		
		docker run --name hoverfly -d -p 8888:8888 -p 8500:8500 spectolabs/hoverfly:latest

		# PROXY
		export HTTP_PROXY="http://localhost:8500"
		export HTTPS_PROXY="http://localhost:8500"

		# copy the command line tool
		# the tool "hoverctl" will be available via the vagrant machine
		cp /home/vagrant/vagrant-home/hoverctl /usr/bin/
		
		# login to the command line tool
		hoverctl login --username hfadmin --password hfpass
		
	SHELL
  
end
