# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
	# The most common configuration options are documented and commented below.
	# For a complete reference, please see the online documentation at
	# https://docs.vagrantup.com.

	# Every Vagrant development environment requires a box. You can search for
	# boxes at https://vagrantcloud.com/search.
	config.vm.box = "boxcutter/ubuntu1604"

	# The url from where the 'config.vm.box' box will be fetched if it
	# doesn't already exist on the user's system.
	config.vm.box_url = "https://app.vagrantup.com/boxcutter/boxes/ubuntu1604"

	# memory increase
	config.vm.provider "virtualbox" do |v|
        v.memory = 8964
        v.cpus = 4
    end
					  
	PATH_VAGRANT_PROJECT=File.dirname(__FILE__)

	
	# forward ports
	
	# openshift
	config.vm.network :forwarded_port, guest: 8443, host: 8443
	config.vm.network :forwarded_port, guest: 53 , host: 53
	config.vm.network :forwarded_port, guest: 80 , host: 80
	config.vm.network :forwarded_port, guest: 443 , host: 443

	
	
	# all files here will be added to home
	config.vm.synced_folder "vagrant-home/", "//root/vagrant-home/"
	
  
	# Use shell script to provision
	config.vm.provision "shell", inline: <<-SHELL
			
		# update
		apt-get update	
		
		
		###############
		##### DOCKER
		
		# install docker
		apt-get -y install docker.io
		
		# tune docker to accept insecure openshift registry by using this configs
		echo -e ' 											
		{   												
			"insecure-registries" : ["172.30.0.0/16"]		
		}													
		' >> /etc/docker/daemon.json

		# tune docker to use "systemd" as cgroupdriver, required to run OpenShift3 on Ubuntu, see https://nology.de/openshift-systemd-is-different-from-docker-cgroup-driver-cgroupfs.html
		sudo chmod 777 /lib/systemd/system/docker.service
		sudo sed -E 's/^(ExecStart.*)/\\1 --exec-opt native.cgroupdriver=systemd/g' -i /lib/systemd/system/docker.service
		
		sudo systemctl daemon-reload
		sudo systemctl restart docker


		
		
		###############
		##### OPENSHIFT
		
		# download openshift
		#https://github.com/openshift/origin/releases/download/v3.6.0/openshift-origin-server-v3.6.0-c4dd4cf-linux-64bit.tar.gz
		
		wget --quiet -O '/home/vagrant/openshift-server.tar.gz' https://github.com/openshift/origin/releases/download/v3.7.0/openshift-origin-server-v3.7.0-7ed6862-linux-64bit.tar.gz
		
		
		
		
	
		# unpack openshift
		mkdir /openshift/
		cd /openshift/
		tar -xf /home/vagrant/openshift-server.tar.gz --directory /openshift/
		mv /openshift/openshift-origin-server*/* /openshift
		rm -rf /openshift/openshift-origin-server*
		chmod -R 777 /openshift/openshift-client
		rm /home/vagrant/openshift-client.tar.gz
		
		# add oc to the path permanently
		echo -e "\n" >> /root/.bashrc
		echo -e 'export PATH=$PATH:/openshift/' >> /root/.bashrc
		source /root/.bashrc
		
		#start openshift
		cd /openshift/
		
		#wont work in vagrant since some functionality is bound to the container-local ip, not localhost. So openshift redirects to this ip, which is not known by host.
		# sudo ./openshift start
		
		# start openshift, bind it to the localhost. Reuse the configs, so that openshift can be restarted without losing configs
		sudo ./oc cluster up --host-data-dir=/data/openshift --use-existing-config --public-hostname=127.0.0.1
		

	SHELL
  
end
